# Generated by Django 4.2.4 on 2023-12-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_user_avatar_alter_userfeedback_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_level",
            field=models.FloatField(
                choices=[
                    (1.0, 1.0),
                    (1.5, 1.5),
                    (2.0, 2.0),
                    (2.5, 2.5),
                    (3.0, 3.0),
                    (3.5, 3.5),
                    (4.0, 4.0),
                    (4.5, 4.5),
                    (5.0, 5.0),
                    (5.5, 5.5),
                ],
                default=1.0,
            ),
        ),
    ]
